### ISSUE TITLE
Store allows array state and converts it to object in `setState`

### ISSUE THREAD

**Issue by anirban09** [fabiospampinato/overstated#11]
When writing a store, its types don't seem to prevent its state from being an array, for example
```typescript
import { Store } from 'overstated';

// no error
class ArrayStore extends Store<string[]> {}
```

But since the `setState` method of the store uses
```typescript
this.state = Object.assign ( {}, this.state, nextState );
```
to update the store state, it always converts the array into an object.

Seems like the store either shouldn't accept a state that is not a plain object, or should handle other types like arrays correctly.

**Comment by fabiospampinato** [comment]
State objects should only be plain objects, I'll see if I can enforce that via the types.

Thanks!

**Comment by fabiospampinato** [comment]
I don't think a `PlainObject` type can currently be constructed in TypeScript, the closest thing I could get is the following:

```ts
type BlackListedMethods = 'copyWithin' | 'name';
type PlainObject = object & { [P in BlackListedMethods]?: never } & { [prop: string]: any; };
```

And when tested against the following declarations:

```ts
const foo00: PlainObject = new class {};
const foo01: PlainObject = {'1':123};
const foo02: PlainObject = {foo:123};
const foo03: PlainObject = {splice: 123};
const foo04: PlainObject = {};
const foo05: PlainObject = [];
const foo06: PlainObject = [123];
const foo07: PlainObject = null;
const foo08: PlainObject = undefined;
const foo09: PlainObject = true;
const foo10: PlainObject = 123;
const foo11: PlainObject = 'asd';
const foo12: PlainObject = function () {};
const foo13: PlainObject = Symbol.iterator;
```

It is able to filters out: primitives, functions, arrays. But it can't filter out classes and, most importantly, objects that set those forbidden methods are also filtered out.

Now, maybe filtering out functions and classes isn't that important, and nobody in their right mind is going to have a `copyWithin` property in their state, so maybe we could just make sure that arrays and primitives are forbidden 🤔 Or/and I could add a note about this in the readme.

@anirban09 what do you think is the best option?

**Comment by fabiospampinato** [comment]
I've added a note in the readme and excluded primitives via the types. I'll be happy to exclude arrays etc. once a "PlainObject" type can be implemented in TS.
