### ISSUE TITLE
A way to undo or at least get previous state?

### ISSUE THREAD

**Issue by rszemplinski** [fabiospampinato/overstated#13]
Hi,

I'm testing out your state management solution and liking what I see so far. Was wondering if you had a built in way to undo-ing state or is that something we would have to manage ourselves? I notice in your debug tool it shows you the previous state but I assume those are just simply printed out and thrown away.

Anyways, thanks for your work!

**Comment by fabiospampinato** [comment]
There are no undo capabilities built-in. 

You could add a middleware which records and stores state as it changes and implement this yourself though.

**Comment by fabiospampinato** [comment]
Would you use this for debugging purposes or do you need this in your app?

**Comment by rszemplinski** [comment]
This would be for app purposes.

**Comment by fabiospampinato** [comment]
I'm asking because otherwise this would be asking for what's called a "time travel debugger".
