### ISSUE TITLE
Question about composed stores but accessing them from lower level components

### ISSUE THREAD

**Issue by rszemplinski** [fabiospampinato/overstated#14]
Hey, it's me again. Sorry!

So I'm loving the fact that I can compose stores together because it's the closest thing I can find to IoC in React. The thing is, my state is looking kinda nasty at the moment because I am shoving everything in the top-level state... for example:

![image](https://user-images.githubusercontent.com/5331990/67055706-1f1c4900-f117-11e9-83be-e3bfb8ebdf37.png)

I was hoping to just pass the store to the lower level and then call `useStore` inside the component and handle stuff from there but it doesn't seem to work. In fact, whenever I pass in any instance into `useStore` I get this error... 

![image](https://user-images.githubusercontent.com/5331990/67055807-833f0d00-f117-11e9-84a5-6f4b371daf13.png)

I guess I'm wondering what I can do to fix this?

**Comment by fabiospampinato** [comment]
How are you defining exampleStore?

**Comment by rszemplinski** [comment]
So it's just another store. The only thing different about it is it has a parent store.  

Just `const exampleStore = new GraphStore()`

**Comment by rszemplinski** [comment]
So after spending way too much time trying to figure this out I found the problem and it was just my stupidity. I apologize for wasting your time on that. 

I would like to know if passing a child store to a child component and using the `useStore` hook inside there is correct/good practice for overstated. Am I thinking about that correctly or should I be approaching this in a different manner?

**Comment by fabiospampinato** [comment]
> So after spending way too much time trying to figure this out I found the problem and it was just my stupidity. I apologize for wasting your time on that.

That's way I was asking to see the code.

> I would like to know if passing a child store to a child component and using the useStore hook inside there is correct/good practice for overstated. Am I thinking about that correctly or should I be approaching this in a different manner?

It's ok I'm doing that too.

**Comment by rszemplinski** [comment]
Thank you for your help!
