### ISSUE TITLE
How to suspend sibling stores?

### ISSUE THREAD

**Issue by avishnyak** [fabiospampinato/overstated#15]
I have a store hierarchy like so:

- Main Store
  - Documents
  - Editors

Each editor may be editing 1 or more documents and each document can be open in more than 1 editor.  Therefore, it cannot be modeled in any simple parent<->child relationship.

I have used compose to wire up the child stores to the parent and enabled autosuspend at the parent level.

However, I keep running into issues where React components are re-rendering if Editors calls a method on Documents via the `this.ctx` method.  This causes the components to re-render in a bad state.

Do you have advice for how to work around this?

**Comment by fabiospampinato** [comment]
I'm not sure I understood the issue completely here, you can always manually suspend a store that's a parent to both of those stores, or you can suspend individual stores manually too I think.

Anyway I'm archiving this repository as I've now moved to something strictly better in my opinion, you should probably do the same too: https://github.com/fabiospampinato/store
