### ISSUE TITLE
Generics...

### ISSUE THREAD

**Issue by lmihalkovic** [fabiospampinato/overstated#2]
... or lack thereof. The generics type system in TypeScipt is far better than Java's and C#'s combined. It seems a waste of that fabulous capability to just put ```.ts``` on a pure Javascript file.

**Comment by fabiospampinato** [comment]
> It seems a waste of that fabulous capability to just put `.ts` on a pure Javascript file.

The point is that once you're ready to implement TS's features you can do so right away.

I had a few difficulties working with generics and react components.

Hopefully the situation will improve once I rewrite this library from scratch.

**Comment by lmihalkovic** [comment]
I made a local version that is partially generisized. Hint: the return type for connect() is React.JSXElementConstructor<P>. I cheated a bit for the type of ```selectr``` and did not include all the details for the {} case, but it works simply. I did not look at all the other modules. I know that this lib is easy to use, but i much prefer to have more control over the state of ui apps.

**Comment by fabiospampinato** [comment]
Closing this as the lib has been rewritten from scratch.
