### ISSUE TITLE
Child component sometimes not re-rendering when using useStore

### ISSUE THREAD

**Issue by richieroldan** [fabiospampinato/overstated#3]
Hi Fabio, First of all thank you for this awesome library. 
I'm having issues regarding useStore. Whenever I use useStore inside a child component and getting only a single value from state, weird stuff happen. But when I try to get the whole state object it works fine. See gif below

Single value from state
![state-single-value](https://user-images.githubusercontent.com/9613793/56450282-663ba400-6357-11e9-8121-6700abc043ed.gif)

Whole state
![whole-state](https://user-images.githubusercontent.com/9613793/56450286-75225680-6357-11e9-9212-7ad0bfb604d9.gif)

Here's an example code
~~~
class ModalStore extends Store{
  state={
    open:false
  }

  openModal = ()=>{
    this.setState({open:true})
  }

  closeModal = ()=>{
    this.setState({open:false})
  }
}

const Modal = ()=>{
  const {state,closeModal} = useStore(ModalStore,store=>({
    closeModal : store.closeModal,
    state : store.state
  })) 

  // Uncomment this to try single state value
  // const {open,closeModal} = useStore(ModalStore,store=>({
  //   closeModal : store.closeModal,
  //   open : store.state.open
  // })) 
  return (
      <div>
        {/* <h1>IsOpen : {JSON.stringify(open)}</h1> */}
        <h1>IsOpen : {JSON.stringify(state)}</h1>
        <button onClick={closeModal}>Close Modal</button>
      </div>
  )
}

const App = ()=>{
  const {openModal} = useStore(ModalStore,store=>({
    openModal : store.openModal
  })) 
  return (
      <div className="App">
          <Modal />
          <button onClick={openModal}>Open Modal</button>
      </div>
  )
}

export default App;
~~~

Here's a git repository of the example code above if you want to take a look.
https://github.com/richieroldan/overstated-usestore-issue.git

P.S. 
I tried using connect and it works fine. The issue is only within useStore hook.

Regards,
Richie

**Comment by fabiospampinato** [comment]
Fixed in `v2.0.0-beta.3`.

Thanks a lot for reporting the issue, this was basically the perfect issue report (gifs, code, a whole repo that reproduces the issue)  👍 

Check [this](https://github.com/fabiospampinato/overstated/commit/9daa0a5644cc6490362779518c33c1b5ef70d9e5) commit if you want to learn more about the fix/root issues.

**Comment by richieroldan** [comment]
Thanks a lot for fixing this issue. This is a big help since we're using your library on our major projects. Will keep the same issue report template on future reports. 😄

Thanks again,
Richie

**Comment by fabiospampinato** [comment]
It would be interesting to hear your feedback after a while that you've been using this library, perhaps there are ways to make it nicer/simpler to use and/or improve it generally in ways that I haven't thought about.
