### ISSUE TITLE
autosuspend 'methodsExclude' not explained in docs

### ISSUE THREAD

**Issue by anirban09** [fabiospampinato/overstated#9]
The docs and comments say the same thing about `methodsInclude` and `methodsExclude`: that methods matching the regex will be autosuspended. I guess the entry for `methodsExclude` is supposed to say that methods matching the regex will _not_ be autosuspended?

**Comment by fabiospampinato** [comment]
My bad, fixed!

**Comment by fabiospampinato** [comment]
Btw I'm in the process of transitioning to Overstated in [Notable](https://github.com/fabiospampinato/notable), once that's done and I don't find any other issue I'll release v2 stable.
